INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(1, 'Africa');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(2, 'Antarctica');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(3, 'Asia');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(4, 'Australia (Ocenia)');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(5, 'Europe');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(6, 'North America');
INSERT INTO CONTINENT(ID, CONTINENTNAME) VALUES(7, 'South America');
