--------------------------------------------------------
--  File created - Sunday-September-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "COVID"."COUNTRY" 
   (	"COUNTRYID" NUMBER(*,0), 
	"CONTINENTID" NUMBER(*,0), 
	"COUNTRYCODE" NVARCHAR2(50), 
	"COUNTRYNAME" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into COVID.COUNTRY
SET DEFINE OFF;
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('1','3','AF','Afghanistan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('2','5','AL','Albania');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('3','1','DZ','Algeria');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('4','5','AD','Andorra');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('5','1','AO','Angola');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('6','6','AI','Anguilla');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('7','6','AG','Antigua and Barbuda');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('8','7','AR','Argentina');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('9','3','AM','Armenia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('10','6','AW','Aruba');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('11','4','AU','Australia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('12','5','AT','Austria');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('13','3','AZ','Azerbaijan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('14','6','BS','Bahamas');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('15','3','BH','Bahrain');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('16','3','BD','Bangladesh');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('17','6','BB','Barbados');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('18','5','BY','Belarus');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('19','5','BE','Belgium');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('20','6','BZ','Belize');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('21','1','BJ','Benin');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('22','6','BM','Bermuda');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('23','3','BT','Bhutan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('24','7','BO','Bolivia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('25','5','BA','Bosnia and Herzegovina');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('26','1','BW','Botswana');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('27','7','BR','Brazil');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('28','6','VG','British Virgin Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('29','3','BN','Brunei');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('30','5','BG','Bulgaria');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('31','1','BF','Burkina Faso');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('32','1','BI','Burundi');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('33','1','CV','Cabo Verde');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('34','3','KH','Cambodia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('35','1','CM','Cameroon');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('36','6','CA','Canada');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('37','1','CF','CAR');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('38','6','BQ','Caribbean Netherlands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('39','6','KY','Cayman Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('40','1','TD','Chad');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('41','5','GB','Channel Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('42','7','CL','Chile');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('43','3','CN','China');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('44','7','CO','Colombia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('45','1','KM','Comoros');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('46','1','CG','Congo');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('47','6','CR','Costa Rica');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('48','5','HR','Croatia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('49','6','CU','Cuba');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('50','6','CW','Curaçao');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('51','3','CY','Cyprus');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('52','5','CZ','Czechia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('53','5','DK','Denmark');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('54','1','DJ','Djibouti');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('55','6','DM','Dominica');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('56','6','DO','Dominican Republic');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('57','1','CD','DRC');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('58','7','EC','Ecuador');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('59','1','EG','Egypt');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('60','6','SV','El Salvador');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('61','1','GQ','Equatorial Guinea');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('62','1','ER','Eritrea');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('63','5','EE','Estonia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('64','1','SZ','Eswatini');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('65','1','ET','Ethiopia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('66','5','FO','Faeroe Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('67','7','FK','Falkland Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('68','4','FJ','Fiji');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('69','5','FI','Finland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('70','5','FR','France');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('71','7','GF','French Guiana');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('72','4','PF','French Polynesia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('73','1','GA','Gabon');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('74','1','GM','Gambia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('75','3','GE','Georgia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('76','5','DE','Germany');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('77','1','GH','Ghana');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('78','5','GI','Gibraltar');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('79','5','GR','Greece');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('80','6','GL','Greenland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('81','6','GD','Grenada');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('82',null,'GP','Guadeloupe');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('83','6','GT','Guatemala');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('84','1','GN','Guinea');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('85','1','GW','Guinea-Bissau');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('86','7','GY','Guyana');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('87','6','HT','Haiti');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('88','6','HN','Honduras');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('89','3','HK','Hong Kong');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('90','5','HU','Hungary');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('91','5','IS','Iceland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('92','3','IN','India');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('93','3','ID','Indonesia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('94','3','IR','Iran');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('95','3','IQ','Iraq');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('96','5','IE','Ireland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('97','5','IM','Isle of Man');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('98','3','IL','Israel');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('99','5','IT','Italy');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('100','1','CI','Ivory Coast');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('101','6','JM','Jamaica');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('102','3','JP','Japan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('103','3','JO','Jordan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('104','3','KZ','Kazakhstan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('105','1','KE','Kenya');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('106','3','KW','Kuwait');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('107','3','KG','Kyrgyzstan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('108','3','LA','Laos');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('109','5','LV','Latvia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('110','3','LB','Lebanon');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('111','1','LS','Lesotho');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('112','1','LR','Liberia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('113','1','LY','Libya');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('114','5','LI','Liechtenstein');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('115','5','LT','Lithuania');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('116','5','LU','Luxembourg');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('117','3','MO','Macao');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('118','1','MG','Madagascar');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('119','1','MW','Malawi');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('120','3','MY','Malaysia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('121','3','MV','Maldives');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('122','1','ML','Mali');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('123','5','MT','Malta');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('124','4','MH','Marshall Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('125','6','MQ','Martinique');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('126','1','MR','Mauritania');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('127',null,'MU','Mauritius');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('128','1','YT','Mayotte');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('129','6','MX','Mexico');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('130','5','MD','Moldova');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('131','5','MC','Monaco');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('132','3','MN','Mongolia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('133','5','ME','Montenegro');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('134','6','MS','Montserrat');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('135','1','MA','Morocco');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('136','1','MZ','Mozambique');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('137',null,null,'MS Zaandam');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('138','3','MM','Myanmar');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('139','1','NA','Namibia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('140','3','NP','Nepal');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('141','5','NL','Netherlands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('142','4','NC','New Caledonia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('143','4','NZ','New Zealand');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('144','6','NI','Nicaragua');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('145','1','NE','Niger');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('146','1','NG','Nigeria');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('147','5','MK','North Macedonia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('148','5','NO','Norway');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('149','3','OM','Oman');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('150','3','PK','Pakistan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('151','3','PS','Palestine');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('152','6','PA','Panama');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('153','4','PG','Papua New Guinea');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('154','7','PY','Paraguay');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('155','7','PE','Peru');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('156','3','PH','Philippines');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('157','5','PL','Poland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('158','5','PT','Portugal');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('159','3','QA','Qatar');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('160','5','RO','Romania');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('161','5','RU','Russia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('162','1','RW','Rwanda');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('163','1','RE','Réunion');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('164','3','KR','S. Korea');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('165','6','KN','Saint Kitts and Nevis');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('166','6','LC','Saint Lucia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('167','6','MF','Saint Martin');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('168','6','PM','Saint Pierre Miquelon');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('169','4','WS','Samoa');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('170','5','SM','San Marino');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('171','1','ST','Sao Tome and Principe');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('172','3','SA','Saudi Arabia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('173','1','SN','Senegal');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('174','5','CS','Serbia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('175','1','SC','Seychelles');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('176','1','SL','Sierra Leone');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('177','3','SG','Singapore');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('178','6','SX','Sint Maarten');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('179','5','SK','Slovakia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('180','5','SI','Slovenia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('181','4','SB','Solomon Islands');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('182','1','SO','Somalia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('183','1','ZA','South Africa');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('184','1','SS','South Sudan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('185','5','ES','Spain');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('186','3','LK','Sri Lanka');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('187','6','BL','St. Barth');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('188','6','VC','St. Vincent Grenadines');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('189','1','SD','Sudan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('190','7','SR','Suriname');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('191','5','SE','Sweden');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('192','5','CH','Switzerland');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('193','3','SY','Syria');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('194','3','TW','Taiwan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('195','3','TJ','Tajikistan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('196','1','TZ','Tanzania');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('197','3','TH','Thailand');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('198','3','TL','Timor-Leste');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('199','1','TG','Togo');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('200','6','TT','Trinidad and Tobago');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('201','1','TN','Tunisia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('202','3','TR','Turkey');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('203','6','TC','Turks and Caicos');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('204','3','AE','UAE');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('205','1','UG','Uganda');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('206','5','GB','UK');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('207','5','UA','Ukraine');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('208','7','UY','Uruguay');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('209','6','US','USA');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('210','3','UZ','Uzbekistan');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('211','4','VU','Vanuatu');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('212','5','VA','Vatican City');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('213','7','VE','Venezuela');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('214','3','VN','Vietnam');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('215','4','WF','Wallis and Futuna');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('216','1','EH','Western Sahara');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('217','3','YE','Yemen');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('218','1','ZM','Zambia');
Insert into COVID.COUNTRY (COUNTRYID,CONTINENTID,COUNTRYCODE,COUNTRYNAME) values ('219','1','ZW','Zimbabwe');
--------------------------------------------------------
--  DDL for Index PK_COUNTRY
--------------------------------------------------------

  CREATE UNIQUE INDEX "COVID"."PK_COUNTRY" ON "COVID"."COUNTRY" ("COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "COVID"."COUNTRY" MODIFY ("COUNTRYID" NOT NULL ENABLE);
  ALTER TABLE "COVID"."COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "COVID"."COUNTRY" ADD CONSTRAINT "FK_CONTINENT_COUNTRY" FOREIGN KEY ("CONTINENTID")
	  REFERENCES "COVID"."CONTINENT" ("ID") ENABLE;
