CREATE TABLE COUNTRY(
COUNTRYID INTEGER NOT NULL,
COUNTRYNAME NVARCHAR2(100),
CONTINENTID INTEGER NOT NULL,

CONSTRAINT PK_COUNTRY PRIMARY KEY(COUNTRYID),
CONSTRAINT FK_CONTINENT_COUNTRY FOREIGN KEY (COUNTRYID) REFERENCES CONTINENT(ID)
);


CREATE TABLE CONTINENT(
ID INTEGER NOT NULL,
CONTINENTNAME NVARCHAR2(100),
COUNTRYID INTEGER NOT NULL,

CONSTRAINT PK_CONTINENT PRIMARY KEY(CONTINENTID)
);


CREATE TABLE STATE_(
ID INTEGER,
STATENAME NVARCHAR2(100),
COUNTRYID INTEGER,

CONSTRAINT PK_STATE PRIMARY KEY(ID),
CONSTRAINT FK_STATE FOREIGN KEY(COUNTRYID) REFERENCES COUNTRY(COUNTRYID)
);



CREATE TABLE CITY(
ID INTEGER,
CITYNAME NVARCHAR2(100),
STATEID INTEGER,

CONSTRAINT PK_CITY PRIMARY KEY,
CONSTRAINT FK_CITY_STATE FOREIGN KEY (STATEID) REFERENCES STATE_(ID)
);


CREATE TABLE AGERANGE(
ID INTEGER,
RANGE NVARCHAR2(50),
RANGENAME NVARCHAR2(50),

CONSTRAINT PK_AGERANGE PRIMARY KEY(ID)

);



CREATE TABLE GENDERAGERANGE(
ID INTEGER,
GENDER CHAR(1),
AGERANGEID INTEGER,
TOTALDEATHS INTEGER,
TOTALCASES INTEGER,

CONSTRAINT PK_GENDERAGERANGE PRIMARY KEY(ID),
CONSTRAINT FK_AGERANGEID FOREIGN KEY(AGERANGEID) REFERENCES AGERANGE(ID)
);



CREATE TABLE CASES(
CASEID INTEGER,
COUNTRYID INTEGER,
STATEID INTEGER,
CITYID INTEGER,
TOTALCASES NUMBER,
NEWCASES NUMBER,
TOTALDEATHS NUMBER,
NEWDEATHS NUMBER,
TOTALRECOVERED NUMBER,
ACTIVECASES NUMBER,
TOTALCASES/1M_ NUMBER,
DEATHS/1M_ NUMBER,
TOTALTESTS NUMBER,
TESTS/1M_ NUMBER,


CONSTRAINT PK_CASEID PRIMARY KEY(CASEID),
CONSTRAINT FK_CASES_COUNTRY FOREIGN KEY(COUNTRYID) REFERENCES COUNTRY(COUNTRYID),
CONSTRAINT FK_CASES_STATE FOREIGN KEY(STATEID) REFERENCES STATE_(ID),
CONSTRAINT FK_CASES_CITY FOREIGN KEY(CITYID) REFERENCES CITY(ID)

);



CREATE TABLE COVID.COUNTRYCASES(
COUNTRYCASESID INTEGER,
COUNTRY_ID INTEGER NOT NULL,
DATE_ DATE,
TOTAL_CASES INTEGER,
NEW_CASES INTEGER,
NEW_CASES_SMOOTHED NUMBER, 
TOTAL_DEATHS INTEGER,
NEW_DEATHS INTEGER,
NEW_DEATHS_SMOOTHED NUMBER,
TOTAL_CASES_PER_MILLION NUMBER,
NEW_CASES_PER_MILLION NUMBER,
NEW_CASES_SMOOTHED_PER_MILLION NUMBER,
TOTAL_DEATHS_PER_MILLION NUMBER,
NEW_DEATHS_PER_MILLION NUMBER,
NEW_DEATHS_SMOOTHED_PER_MILLION NUMBER,
REPRODUCTION_RATE NUMBER,
ICU_PATIENTS INTEGER, 
ICU_PATIENTS_PER_MILLION NUMBER,
HOSP_PATIENTS INTEGER,
HOSP_PATIENTS_PER_MILLION NUMBER,
WEEKLY_ICU_ADMISSIONS NUMBER,
WEEKLY_ICU_ADMISSIONS_PER_MILLION NUMBER,
WEEKLY_HOSP_ADMISSIONS NUMBER,
WEEKLY_HOSP_ADMISSIONS_PER_MILLION NUMBER,
NEW_TESTS INTEGER,
TOTAL_TESTS INTEGER,
TOTAL_TESTS_PER_THOUSAND NUMBER,
NEW_TESTS_PER_THOUSAND NUMBER, 
NEW_TESTS_SMOOTHED INTEGER,
NEW_TESTS_SMOOTHED_PER_THOUSAND NUMBER,
POSITIVE_RATE NUMBER,
TESTS_PER_CASE NUMBER,
TESTS_UNITS VARCHAR(100),
TOTAL_VACCINATIONS INTEGER,
NEW_VACCINATIONS INTEGER,
TOTAL_VACCINATIONS_PER_HUNDRED NUMBER,
NEW_VACCINATIONS_PER_MILLION NUMBER,
STRINGENCY_INDEX NUMBER, 
POPULATION_ INTEGER, 
POPULATION_DENSITY NUMBER,
MEDIAN_AGE NUMBER,
AGED_65_OLDER NUMBER,
AGED_70_OLDER NUMBER,
GDP_PER_CAPITA NUMBER,
EXTREME_POVERTY NUMBER,
CARDIOVASC_DEATH_RATE NUMBER,
DIABETES_PREVALENCE NUMBER, 
FEMALE_SMOKERS NUMBER,
MALE_SMOKERS NUMBER,
HANDWASHING_FACILITIES NUMBER,
HOSPITAL_BEDS_PER_THOUSAND NUMBER,
LIFE_EXPECTANCY NUMBER,
HUMAN_DEVELOPMENT_INDEX NUMBER,

CONSTRAINT PK_COUNTRYCASES PRIMARY KEY(COUNTRYCASESID)
CONSTRAINT FK_CASES_BY_COUNTRIES FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(COUNTRYID)
);