-- ÜLKELERDE YAPILAN TOPLAM TEST SAYISI

SELECT C.COUNTRYNAME, MAX(TOTAL_TESTS) TOTALTESTS
    FROM COUNTRYCASES CC
	INNER JOIN COUNTRY C ON C.COUNTRYID=CC.COUNTRY_ID
	GROUP BY C.COUNTRYNAME
	HAVING MAX(TOTAL_TESTS) IS NOT NULL
	ORDER BY MAX(TOTAL_TESTS) DESC;