--Eyaletlerde toplam vefat sayısı

SELECT S.STATENAME, SC.STATECODE, MAX(SC.DEATH)
FROM STATECASES SC
INNER JOIN STATE_ S ON S.STATECODE=SC.STATECODE
GROUP BY S.STATENAME, SC.STATECODE
HAVING SUM(POSITIVETESTSVIRAL) IS NULL
ORDER BY 3 DESC;