-- ABD EYALETLERİ TOPLAM TEST SAYILARI

SELECT SC.STATECODE, STATENAME, MAX(TOTALTESTVIRAL) TOTALTESTS
FROM STATECASES SC
	INNER JOOIN STATE_ SON S.STATECODE=SC.STATECODE
	GROUP BY SC.STATECODE, STATENAME
	HAVING MAX(TOTALTESTVIRAL) IS NOT NULL
	ORDER BY 3 DESC;