--NEW YORK 6 OCAK 2021 COVID VERİLERİ

SELECT * FROM
(
	SELECT SC.STATECODE, S.STATENAME, DATE_, S.POPULATION, S.AREA, SC.DEATHINCREASE, SC.DEATH, SC.RECOVERED
	FROM STATECASES SC
		INNER JOIN STATE_ S ON S.STATECODE=SC.STATECODE
		WHERE SC.STATECODE='NY'
		ORDER BY DATE_ DESC

)
WHERE ROWNUM=1;