--TOPLAM TEST SAYISI

SELECT SUM(MAX(TOTALTESTVIRAL)) USTOTALTESTS
	FROM STATECASES SC
	INNER JOIN STATE_ S ON S.STATECODE=SC.STATECODE
	GROUP BY SC.STATECODE, STATENAME
	HAVING MAX(TOTALTESTVIRAL) IS NOT NULL;