--TÜRKİYE'DE SİGARA İÇME ORANI

SELECT CC.FEMALE_SMOKERS WOMEN_SMOKERS, CC.MALE_SMOKERS MEN_SMOKERS, C.COUNTRYNAME
	FROM COUNTRYCASES CC
	INNER JOIN COUNTRY C ON C.COUNTRYID=CC.COUNTRY_ID
	WHERE CC.FEMALE_SMOKERS IS NOT NULL
	AND CC.MALE_SMOKERS IS NOT NULL
	AND CC.COUNTRY_ID=202
	GROUP BY CC.FEMALE_SMOKERS, CC.MALE_SMOKERS, C.COUNTRYNAME
	ORDER BY 1 DESC;
