-- TÜRKİYE TOPLAM VAKA SAYISI

SELECT MAX(CC.TOTAL_CASES), C.COUNTRYNAME
	FROM COUNTRYCASES CC
	INNER JOIN COUNTRY C ON C.COUNTRYID=CC.COUNTRY_ID
	WHERE CC.COUNTRY_ID=202
	GROUP BY C.COUNTRYNAME
	HAVING MAX(CC.TOTAL_DEATHS) IS NOT NULL
	ORDER BY 1;