create or replace NONEDITIONABLE PROCEDURE STATETOTALDEATH
AS
V_TOTALDEATH INTEGER:=0;

BEGIN
    --TOPLAM TEST SAYISI
    SELECT SUM(MAX(SC.DEATH)) INTO V_TOTALDEATH
    FROM STATECASES SC
    INNER JOIN STATE_ S ON SC.STATECODE=S.STATECODE
    GROUP BY SC.STATECODE;
    DBMS_OUTPUT.PUT_LINE('US TOTALDEATH: ' || V_TOTALDEATH);
END;



--EXECUTE

EXEC STATETOTALDEATH;
