CREATE OR REPLACE PROCEDURE FINDTOTAL
(
P_DATE IN DATE,
P_COUNTRYCODE IN VARCHAR2,
P_TOTALCASES OUT INTEGER,
P_TOTALTESTS OUT INTEGER,
P_TOTALDEATHS OUT INTEGER,
P_NEWCASES OUT INTEGER,
P_NEWDEATHS OUT INTEGER,
P_NEWTESTS OUT INTEGER
)
AS
BEGIN
    SELECT CC.TOTAL_CASES, CC.TOTAL_TESTS, CC.TOTAL_DEATHS, CC.NEW_CASES, CC.NEW_DEATHS, CC.NEW_TESTS INTO
                P_TOTALCASES, P_TOTALTESTS, P_TOTALDEATHS, P_NEWCASES, P_NEWDEATHS, P_NEWTESTS
    FROM COUNTRYCASES CC 
        INNER JOIN COUNTRY C ON C.COUNTRYID=CC.COUNTRY_ID
        WHERE 1=1
        AND C.COUNTRYCODE=P_COUNTRYCODE
        AND CC.DATE_=P_DATE;
END;





--EXECUTE
DECLARE
V_DATE DATE                := '06/01/2021';
V_COUNTRYCODE VARCHAR2(3)  := 'TR';
V_TOTALCASES INTEGER;
V_TOTALTESTS INTEGER;
V_TOTALDEATHS INTEGER;
V_NEWCASES INTEGER;
V_NEWDEATHS INTEGER;
V_NEWTESTS INTEGER;

BEGIN
        FINDTOTAL(V_DATE,V_COUNTRYCODE, V_TOTALCASES, V_TOTALTESTS, V_TOTALDEATHS, V_NEWCASES, V_NEWDEATHS, V_NEWTESTS);
        DBMS_OUTPUT.PUT_LINE('Date         : ' || V_DATE);
        DBMS_OUTPUT.PUT_LINE('CountryCode  : ' || V_COUNTRYCODE);
        DBMS_OUTPUT.PUT_LINE('TotalCase    : ' || V_TOTALCASES);
        DBMS_OUTPUT.PUT_LINE('TotalTests   : ' || V_TOTALTESTS);
        DBMS_OUTPUT.PUT_LINE('TotalDeaths  : ' || V_TOTALDEATHS);
        DBMS_OUTPUT.PUT_LINE('NewCases     : ' || V_NEWCASES);
        DBMS_OUTPUT.PUT_LINE('NewDeaths    : ' || V_NEWDEATHS);
        DBMS_OUTPUT.PUT_LINE('NewTests     : ' || V_NEWTESTS);
END;